ssh.exp: Don't append "rm -f $program" to the commandline
This is preventing me from using `set_board_info connect ssh`, since the
rm -f $program results in ssh failing while running the initial mkdir
in remote_download: `[remote_exec $dest mkdir "-p $remotedir"]`.
I added some debugging prints to show the resulting ssh command and error
output:
```
OVERRIDING PROGRAM due to board_info remote-cheribsd exists remotedir: original='mkdir'
Executing on remote-cheribsd: test -d /tmp/runtest.67607 && cd /tmp/runtest.67607; mkdir -p /tmp/runtest.67607
ABOUT TO RUN: ssh   -p 56002 -o ControlPersist=yes -o ControlMaster=auto -o ControlPath="/tmp/ssh-%r@%h:%p" root@localhost sh -c 'test -d /tmp/runtest.67607 && cd /tmp/runtest.67607; mkdir -p /tmp/runtest.67607 2>&1 && echo XYZ\${?}ZYX \; rm -f test -d /tmp/runtest.67607 && cd /tmp/runtest.67607; mkdir'
spawn [open ...]
pid is 67646 67647 -67646 -67647
XYZ0ZYX
rm: /tmp/runtest.67607: is a directory
usage: mkdir [-pv] [-m mode] directory_name ...
pid is -1
close result is child process exited abnormally
output is XYZ0ZYX
rm: /tmp/runtest.67607: is a directory
usage: mkdir [-pv] [-m mode] directory_name ...
 status 1
ssh status is 1, output is XYZ0ZYX
rm: /tmp/runtest.67607: is a directory
usage: mkdir [-pv] [-m mode] directory_name ...

ERROR: Couldn't create remote directory /tmp/runtest.67607 on remote-cheribsd
```

I am not sure why the rm -f was added here in the first place, since
rsh.exp does not have it. Dropping it allows me to test remotely via ssh
to a FreeBSD system.